name: 999._DDV -> vpn-on
color: null
values:
  - key: url-adm-web
    value: http://223.62.243.50:9099
    enabled: true
  - key: url-adm-api
    value: http://223.62.243.50:8088
    enabled: true
  - key: url-was-api
    value: http://223.62.243.49:8080/tsafeApi/v4/
    enabled: true
  - key: guardianSeq
    value: "2"
    enabled: true
  - key: childSeq
    value: "803395"
    enabled: true
  - key: childPhone
    value: "01053211760"
    enabled: true
  - key: guardianPhone
    value: "01094988624"
    enabled: true
