$kind: http-request
url: "{{url-api}}/api/v1/config"
method: GET
body:
  type: json
  content: |-
    {
        "key":"rescue",
        "value":"Y"
    }
auth:
  type: bearer
  credentials:
    token: "{{token}}"
settings: {}
order: 4000
