$kind: http-request
url: "{{url-was-api}}getAppConfig"
method: POST
headers:
  phoneNumber: "01094988624"
  deviceId: device-id
  prodId: ""
  apiToken: EpprhhFHhWK6C6WBDDCEubw01iqLU5ck4rdIyj66mX8={{childSeq}}
body:
  type: json
  content: |-
    {
        "configKey": "PACKAGE_NAME_APP_LIMIT"
    }
settings: {}
order: 4000
