$kind: http-request
name: v4/children/getAppConfig
url: "{{svr-https-tsafe-api}}/v4/children/getAppConfig"
method: POST
headers:
  - key: apiToken
    value: "{{refreshAccessToken}}"
  - key: prodId
    value: NA00004907
    description: 유해차단
body:
  type: text
  content: |-
    {
        "configKey" : "GOOGLE_TESTER_HAZARD_PHONE_NUMBER"
    }
auth:
  type: noauth
settings: {}
order: 2000
